component: multi-scf
name: mirrorrim-tencent

inputs:
  src:
    src: ./
    exclude:
      - .env
      - "node_modules/**"
  environments:
    - key: PG_CONNECT_STRING
      value: ${output:${stage}:${app}:mirrorrim-tencent-DB.private.connectionString}
    - key: CLIENT_ID
      value: ${env:CLIENT_ID}
    - key: CLIENT_SECRET
      value: ${env:CLIENT_SECRET}
    - key: RSF_STATE
      value: ${env:RSF_STATE}
  region: ap-shanghai
  runtime: Nodejs12.16
  memorySize: 128
  vpc:
    vpcId: ${output:${stage}:${app}:mirrorrim-tencent-vpc.vpcId} # 私有网络Id
    subnetId: ${output:${stage}:${app}:mirrorrim-tencent-vpc.subnetId} # 子网Id
  installDependency: true # 是否在线安装依赖
  timeout: 10
  functions:
    fire:
      handler: mirrorrim.fire
      memorySize: 256
    progress:
      handler: mirrorrim.queryExportProgress
      timeout: 15
    export:
      handler: mirrorrim.asyncExport
      timeout: 15
  triggers:
    - type: apigw
      parameters:
        name: mirrorrimAPIGW
        protocols:
          - https
          - http
        apis:
          - path: /fire
            method: GET
            # api 的 function 配置优先级高于外层 function
            function: fire
            param:
              - name: code
                position: QUERY
                required: true
                type: string
                desc: code from OAuth
              - name: state
                position: QUERY
                required: true
                type: string
                desc: state from OAuth
          - path: /export
            method: GET
            function: export
            param:
              - name: token
                position: QUERY
                required: true
                type: string
                desc: user_id
              - name: doc_id
                position: QUERY
                required: true
                type: string
                desc: id for requested tencent doc
          - path: /progress
            method: GET
            function: export
            param:
              - name: token
                position: QUERY
                required: true
                type: string
                desc: user_id
              - name: doc_id
                position: QUERY
                required: true
                type: string
                desc: id for requested tencent doc
              - name: operation_id
                position: QUERY
                required: true
                type: string
                desc: operation_id for requested tencent doc
