component: multi-scf
name: sls-demo-msn

inputs:
  src:
    src: ./
    exclude:
      - .env
      - "node_modules/**"
  environments:
    - key: PG_CONNECT_STRING
      value: ${output:${stage}:${app}:sls-demo-msn-DB.private.connectionString}
  region: ap-guangzhou
  runtime: Nodejs12.16
  memorySize: 128
  vpc:
    vpcId: ${output:${stage}:${app}:sls-demo-msn-vpc.vpcId} # 私有网络Id
    subnetId: ${output:${stage}:${app}:sls-demo-msn-vpc.subnetId} # 子网Id
  installDependency: true # 是否在线安装依赖
  timeout: 10
  functions:
    allTodo:
      handler: todos.all
      memorySize: 256
    addTodo:
      handler: todos.add
      timeout: 15
    completeTodo:
      handler: todos.comp
      timeout: 15
  triggers:
    - type: apigw
      parameters:
        name: todosAPIGW
        protocols:
          - https
          - http
        apis:
          - path: /todos/
            method: GET
            # api 的 function 配置优先级高于外层 function
            function: allTodo
          - path: /todos/
            method: POST
            # api 的 function 配置优先级高于外层 function
            function: addTodo
          - path: /todos/{id}/actions/complete
            method: POST
            function: completeTodo
            param:
              - name: id
                position: PATH
                required: true
                type: number
                desc: Todo ID
